name: Teste da aplicação
run-name: ${{ github.actor }} is testing the aplication
on: [push]
jobs:
  Teste:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install JDK 17
        run: |
          wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb && sudo apt install jdk-17_linux-x64_bin.deb
      - name: Teste da aplicação
        run: |
          ls {{ github.workspace }}
          cd {{ github.workspace }}
          javac HtmlAnalyzer.java
          java HtmlAnalyzer https://docs.github.com/en/actions/quickstart
      - run: echo "🍏 This job's status is ${{ job.status }}."
